export const colors = {
  backgroundTop: '#1a0505',
  backgroundBottom: '#3d1208',
  saffron: '#FF9933',
  saffronLight: '#FFB366',
  gold: '#FFD700',
  goldDark: '#C9A227',
  maroon: '#5c0a0a',
  cream: '#FFF8E7',
  creamMuted: 'rgba(255, 248, 231, 0.65)',
  beadInactive: 'rgba(255, 153, 51, 0.22)',
  beadActive: '#FFD700',
  beadGlow: '#FF9933',
  overlay: 'rgba(0, 0, 0, 0.72)',
  success: '#2ecc71',
  buttonShadow: 'rgba(255, 153, 51, 0.45)',
};

export const TOTAL_COUNT = 108;

export const copy = {
  appTitle: '108 Counter',
  subtitle: 'Mala · Mantra · Parikrama',
  tapHint: 'Tap to count',
  malaLabel: 'Mala',
  countLabel: 'Beads',
  malaCompleted: 'Malas completed',
  malaNone: '—',
  roundLabel: 'Round',
  remaining: 'Remaining',
  completeTitle: '108 Complete',
  completeMessage: 'One full mala round finished. Tap below to begin the next.',
  continue: 'Start Next 108',
  resetCount: 'Reset Count',
  resetMalas: 'Reset Malas',
  reset: 'Reset',
  undo: 'Undo',
  haptics: 'Haptics',
  history: 'History',
  historyTitle: 'Mala History',
  historyEmpty: 'Complete your first 108 to see history here.',
  clearHistory: 'Clear History',
  counterModeTitle: 'Counting mode',
  counterModeMalaHint: 'One mala at a time — stops at 108 with celebration.',
  counterModeJaapHint: 'Continuous naam jaap — keep tapping up to 10 crore.',
  modeMala: '108 Mala',
  modeJaap: 'Naam jaap',
  switchModeTitle: 'Switch counting mode?',
  switchModeMessage:
    'Each mode keeps its own count. Your progress in both modes is saved when you switch.',
  jaapTotal: 'Total jaap',
  jaapTapHint: 'Tap to continue',
  jaapTapCircle: 'Tap the circle to count',
  jaapSubtitle: 'Mala · Mantra · Naam jaap',
  resetJaap: 'Reset jaap count',
  resetJaapConfirm: 'Reset your total naam jaap count to zero?',
  jaapMaxReached: 'You have reached 10 crore. Reset to start again.',
  malaDailyResetTitle: 'Daily mala reset',
  malaDailyResetDescription:
    'When on, bead count, completed malas, and history reset at the start of each day. When off, counts continue across days.',
};
