/** Purnima & Amavasya dates/times for India (IST). Generated by scripts/generate-lunar-days.mjs */

export type LunarDayKind = 'purnima' | 'amavasya';

export type LunarTiming = {
  date: string;
  time: string;
  label: string;
};

export type LunarDay = {
  date: string;
  kind: LunarDayKind;
  begins: LunarTiming;
  ends: LunarTiming;
};

export const lunarDays2025: LunarDay[] = [
  {
    "date": "2025-01-13",
    "kind": "purnima",
    "begins": {
      "date": "2025-01-13",
      "time": "05:03 AM",
      "label": "05:03 AM, Jan 13"
    },
    "ends": {
      "date": "2025-01-14",
      "time": "03:56 AM",
      "label": "03:56 AM, Jan 14"
    }
  },
  {
    "date": "2025-01-29",
    "kind": "amavasya",
    "begins": {
      "date": "2025-01-28",
      "time": "07:35 PM",
      "label": "07:35 PM, Jan 28"
    },
    "ends": {
      "date": "2025-01-29",
      "time": "06:05 PM",
      "label": "06:05 PM, Jan 29"
    }
  },
  {
    "date": "2025-02-12",
    "kind": "purnima",
    "begins": {
      "date": "2025-02-11",
      "time": "06:55 PM",
      "label": "06:55 PM, Feb 11"
    },
    "ends": {
      "date": "2025-02-12",
      "time": "07:22 PM",
      "label": "07:22 PM, Feb 12"
    }
  },
  {
    "date": "2025-02-27",
    "kind": "amavasya",
    "begins": {
      "date": "2025-02-27",
      "time": "08:54 AM",
      "label": "08:54 AM, Feb 27"
    },
    "ends": {
      "date": "2025-02-28",
      "time": "06:14 AM",
      "label": "06:14 AM, Feb 28"
    }
  },
  {
    "date": "2025-03-14",
    "kind": "purnima",
    "begins": {
      "date": "2025-03-13",
      "time": "10:35 AM",
      "label": "10:35 AM, Mar 13"
    },
    "ends": {
      "date": "2025-03-14",
      "time": "12:23 PM",
      "label": "12:23 PM, Mar 14"
    }
  },
  {
    "date": "2025-03-29",
    "kind": "amavasya",
    "begins": {
      "date": "2025-03-28",
      "time": "07:55 PM",
      "label": "07:55 PM, Mar 28"
    },
    "ends": {
      "date": "2025-03-29",
      "time": "04:27 PM",
      "label": "04:27 PM, Mar 29"
    }
  },
  {
    "date": "2025-04-12",
    "kind": "purnima",
    "begins": {
      "date": "2025-04-12",
      "time": "03:21 AM",
      "label": "03:21 AM, Apr 12"
    },
    "ends": {
      "date": "2025-04-13",
      "time": "05:51 AM",
      "label": "05:51 AM, Apr 13"
    }
  },
  {
    "date": "2025-04-27",
    "kind": "amavasya",
    "begins": {
      "date": "2025-04-27",
      "time": "04:49 AM",
      "label": "04:49 AM, Apr 27"
    },
    "ends": {
      "date": "2025-04-28",
      "time": "01:00 AM",
      "label": "01:00 AM, Apr 28"
    }
  },
  {
    "date": "2025-05-12",
    "kind": "purnima",
    "begins": {
      "date": "2025-05-11",
      "time": "08:01 PM",
      "label": "08:01 PM, May 11"
    },
    "ends": {
      "date": "2025-05-12",
      "time": "10:25 PM",
      "label": "10:25 PM, May 12"
    }
  },
  {
    "date": "2025-05-26",
    "kind": "amavasya",
    "begins": {
      "date": "2025-05-26",
      "time": "12:11 PM",
      "label": "12:11 PM, May 26"
    },
    "ends": {
      "date": "2025-05-27",
      "time": "08:31 AM",
      "label": "08:31 AM, May 27"
    }
  },
  {
    "date": "2025-06-11",
    "kind": "purnima",
    "begins": {
      "date": "2025-06-10",
      "time": "11:35 AM",
      "label": "11:35 AM, Jun 10"
    },
    "ends": {
      "date": "2025-06-11",
      "time": "01:13 PM",
      "label": "01:13 PM, Jun 11"
    }
  },
  {
    "date": "2025-06-25",
    "kind": "amavasya",
    "begins": {
      "date": "2025-06-24",
      "time": "06:59 PM",
      "label": "06:59 PM, Jun 24"
    },
    "ends": {
      "date": "2025-06-25",
      "time": "04:00 PM",
      "label": "04:00 PM, Jun 25"
    }
  },
  {
    "date": "2025-07-10",
    "kind": "purnima",
    "begins": {
      "date": "2025-07-10",
      "time": "01:36 AM",
      "label": "01:36 AM, Jul 10"
    },
    "ends": {
      "date": "2025-07-11",
      "time": "02:06 AM",
      "label": "02:06 AM, Jul 11"
    }
  },
  {
    "date": "2025-07-24",
    "kind": "amavasya",
    "begins": {
      "date": "2025-07-24",
      "time": "02:28 AM",
      "label": "02:28 AM, Jul 24"
    },
    "ends": {
      "date": "2025-07-25",
      "time": "12:40 AM",
      "label": "12:40 AM, Jul 25"
    }
  },
  {
    "date": "2025-08-09",
    "kind": "purnima",
    "begins": {
      "date": "2025-08-08",
      "time": "02:12 PM",
      "label": "02:12 PM, Aug 08"
    },
    "ends": {
      "date": "2025-08-09",
      "time": "01:24 PM",
      "label": "01:24 PM, Aug 09"
    }
  },
  {
    "date": "2025-08-22",
    "kind": "amavasya",
    "begins": {
      "date": "2025-08-22",
      "time": "11:55 AM",
      "label": "11:55 AM, Aug 22"
    },
    "ends": {
      "date": "2025-08-23",
      "time": "11:35 AM",
      "label": "11:35 AM, Aug 23"
    }
  },
  {
    "date": "2025-09-07",
    "kind": "purnima",
    "begins": {
      "date": "2025-09-07",
      "time": "01:41 AM",
      "label": "01:41 AM, Sep 07"
    },
    "ends": {
      "date": "2025-09-07",
      "time": "11:38 PM",
      "label": "11:38 PM, Sep 07"
    }
  },
  {
    "date": "2025-09-21",
    "kind": "amavasya",
    "begins": {
      "date": "2025-09-21",
      "time": "12:16 AM",
      "label": "12:16 AM, Sep 21"
    },
    "ends": {
      "date": "2025-09-22",
      "time": "01:23 AM",
      "label": "01:23 AM, Sep 22"
    }
  },
  {
    "date": "2025-10-07",
    "kind": "purnima",
    "begins": {
      "date": "2025-10-06",
      "time": "12:23 PM",
      "label": "12:23 PM, Oct 06"
    },
    "ends": {
      "date": "2025-10-07",
      "time": "09:16 AM",
      "label": "09:16 AM, Oct 07"
    }
  },
  {
    "date": "2025-10-21",
    "kind": "amavasya",
    "begins": {
      "date": "2025-10-20",
      "time": "03:44 PM",
      "label": "03:44 PM, Oct 20"
    },
    "ends": {
      "date": "2025-10-21",
      "time": "05:54 PM",
      "label": "05:54 PM, Oct 21"
    }
  },
  {
    "date": "2025-11-05",
    "kind": "purnima",
    "begins": {
      "date": "2025-11-04",
      "time": "10:36 PM",
      "label": "10:36 PM, Nov 04"
    },
    "ends": {
      "date": "2025-11-05",
      "time": "06:48 PM",
      "label": "06:48 PM, Nov 05"
    }
  },
  {
    "date": "2025-11-19",
    "kind": "amavasya",
    "begins": {
      "date": "2025-11-19",
      "time": "09:43 AM",
      "label": "09:43 AM, Nov 19"
    },
    "ends": {
      "date": "2025-11-20",
      "time": "12:16 PM",
      "label": "12:16 PM, Nov 20"
    }
  },
  {
    "date": "2025-12-04",
    "kind": "purnima",
    "begins": {
      "date": "2025-12-04",
      "time": "08:37 AM",
      "label": "08:37 AM, Dec 04"
    },
    "ends": {
      "date": "2025-12-05",
      "time": "04:43 AM",
      "label": "04:43 AM, Dec 05"
    }
  },
  {
    "date": "2025-12-19",
    "kind": "amavasya",
    "begins": {
      "date": "2025-12-19",
      "time": "04:59 AM",
      "label": "04:59 AM, Dec 19"
    },
    "ends": {
      "date": "2025-12-20",
      "time": "07:12 AM",
      "label": "07:12 AM, Dec 20"
    }
  }
];

export const lunarDays2026: LunarDay[] = [
  {
    "date": "2026-01-03",
    "kind": "purnima",
    "begins": {
      "date": "2026-01-02",
      "time": "06:53 PM",
      "label": "06:53 PM, Jan 02"
    },
    "ends": {
      "date": "2026-01-03",
      "time": "03:32 PM",
      "label": "03:32 PM, Jan 03"
    }
  },
  {
    "date": "2026-01-18",
    "kind": "amavasya",
    "begins": {
      "date": "2026-01-18",
      "time": "12:03 AM",
      "label": "12:03 AM, Jan 18"
    },
    "ends": {
      "date": "2026-01-19",
      "time": "01:21 AM",
      "label": "01:21 AM, Jan 19"
    }
  },
  {
    "date": "2026-02-01",
    "kind": "purnima",
    "begins": {
      "date": "2026-02-01",
      "time": "05:52 AM",
      "label": "05:52 AM, Feb 01"
    },
    "ends": {
      "date": "2026-02-02",
      "time": "03:38 AM",
      "label": "03:38 AM, Feb 02"
    }
  },
  {
    "date": "2026-02-17",
    "kind": "amavasya",
    "begins": {
      "date": "2026-02-16",
      "time": "05:34 PM",
      "label": "05:34 PM, Feb 16"
    },
    "ends": {
      "date": "2026-02-17",
      "time": "05:30 PM",
      "label": "05:30 PM, Feb 17"
    }
  },
  {
    "date": "2026-03-03",
    "kind": "purnima",
    "begins": {
      "date": "2026-03-02",
      "time": "05:55 PM",
      "label": "05:55 PM, Mar 02"
    },
    "ends": {
      "date": "2026-03-03",
      "time": "05:07 PM",
      "label": "05:07 PM, Mar 03"
    }
  },
  {
    "date": "2026-03-18",
    "kind": "amavasya",
    "begins": {
      "date": "2026-03-18",
      "time": "08:25 AM",
      "label": "08:25 AM, Mar 18"
    },
    "ends": {
      "date": "2026-03-19",
      "time": "06:52 AM",
      "label": "06:52 AM, Mar 19"
    }
  },
  {
    "date": "2026-04-02",
    "kind": "purnima",
    "begins": {
      "date": "2026-04-01",
      "time": "07:06 AM",
      "label": "07:06 AM, Apr 01"
    },
    "ends": {
      "date": "2026-04-02",
      "time": "07:41 AM",
      "label": "07:41 AM, Apr 02"
    }
  },
  {
    "date": "2026-04-17",
    "kind": "amavasya",
    "begins": {
      "date": "2026-04-16",
      "time": "08:11 PM",
      "label": "08:11 PM, Apr 16"
    },
    "ends": {
      "date": "2026-04-17",
      "time": "05:21 PM",
      "label": "05:21 PM, Apr 17"
    }
  },
  {
    "date": "2026-05-01",
    "kind": "purnima",
    "begins": {
      "date": "2026-04-30",
      "time": "09:12 PM",
      "label": "09:12 PM, Apr 30"
    },
    "ends": {
      "date": "2026-05-01",
      "time": "10:52 PM",
      "label": "10:52 PM, May 01"
    }
  },
  {
    "date": "2026-05-16",
    "kind": "amavasya",
    "begins": {
      "date": "2026-05-16",
      "time": "05:11 AM",
      "label": "05:11 AM, May 16"
    },
    "ends": {
      "date": "2026-05-17",
      "time": "01:30 AM",
      "label": "01:30 AM, May 17"
    }
  },
  {
    "date": "2026-05-31",
    "kind": "purnima",
    "begins": {
      "date": "2026-05-30",
      "time": "11:57 AM",
      "label": "11:57 AM, May 30"
    },
    "ends": {
      "date": "2026-05-31",
      "time": "02:14 PM",
      "label": "02:14 PM, May 31"
    }
  },
  {
    "date": "2026-06-14",
    "kind": "amavasya",
    "begins": {
      "date": "2026-06-14",
      "time": "12:19 PM",
      "label": "12:19 PM, Jun 14"
    },
    "ends": {
      "date": "2026-06-15",
      "time": "08:23 AM",
      "label": "08:23 AM, Jun 15"
    }
  },
  {
    "date": "2026-06-29",
    "kind": "purnima",
    "begins": {
      "date": "2026-06-29",
      "time": "03:06 AM",
      "label": "03:06 AM, Jun 29"
    },
    "ends": {
      "date": "2026-06-30",
      "time": "05:26 AM",
      "label": "05:26 AM, Jun 30"
    }
  },
  {
    "date": "2026-07-14",
    "kind": "amavasya",
    "begins": {
      "date": "2026-07-13",
      "time": "06:49 PM",
      "label": "06:49 PM, Jul 13"
    },
    "ends": {
      "date": "2026-07-14",
      "time": "03:12 PM",
      "label": "03:12 PM, Jul 14"
    }
  },
  {
    "date": "2026-07-29",
    "kind": "purnima",
    "begins": {
      "date": "2026-07-28",
      "time": "06:18 PM",
      "label": "06:18 PM, Jul 28"
    },
    "ends": {
      "date": "2026-07-29",
      "time": "08:05 PM",
      "label": "08:05 PM, Jul 29"
    }
  },
  {
    "date": "2026-08-12",
    "kind": "amavasya",
    "begins": {
      "date": "2026-08-12",
      "time": "01:52 AM",
      "label": "01:52 AM, Aug 12"
    },
    "ends": {
      "date": "2026-08-12",
      "time": "11:06 PM",
      "label": "11:06 PM, Aug 12"
    }
  },
  {
    "date": "2026-08-28",
    "kind": "purnima",
    "begins": {
      "date": "2026-08-27",
      "time": "09:08 AM",
      "label": "09:08 AM, Aug 27"
    },
    "ends": {
      "date": "2026-08-28",
      "time": "09:48 AM",
      "label": "09:48 AM, Aug 28"
    }
  },
  {
    "date": "2026-09-10",
    "kind": "amavasya",
    "begins": {
      "date": "2026-09-10",
      "time": "10:33 AM",
      "label": "10:33 AM, Sep 10"
    },
    "ends": {
      "date": "2026-09-11",
      "time": "08:56 AM",
      "label": "08:56 AM, Sep 11"
    }
  },
  {
    "date": "2026-09-26",
    "kind": "purnima",
    "begins": {
      "date": "2026-09-25",
      "time": "11:06 PM",
      "label": "11:06 PM, Sep 25"
    },
    "ends": {
      "date": "2026-09-26",
      "time": "10:18 PM",
      "label": "10:18 PM, Sep 26"
    }
  },
  {
    "date": "2026-10-10",
    "kind": "amavasya",
    "begins": {
      "date": "2026-10-09",
      "time": "09:35 PM",
      "label": "09:35 PM, Oct 09"
    },
    "ends": {
      "date": "2026-10-10",
      "time": "09:19 PM",
      "label": "09:19 PM, Oct 10"
    }
  },
  {
    "date": "2026-10-26",
    "kind": "purnima",
    "begins": {
      "date": "2026-10-25",
      "time": "11:55 AM",
      "label": "11:55 AM, Oct 25"
    },
    "ends": {
      "date": "2026-10-26",
      "time": "09:41 AM",
      "label": "09:41 AM, Oct 26"
    }
  },
  {
    "date": "2026-11-08",
    "kind": "amavasya",
    "begins": {
      "date": "2026-11-08",
      "time": "11:27 AM",
      "label": "11:27 AM, Nov 08"
    },
    "ends": {
      "date": "2026-11-09",
      "time": "12:31 PM",
      "label": "12:31 PM, Nov 09"
    }
  },
  {
    "date": "2026-11-24",
    "kind": "purnima",
    "begins": {
      "date": "2026-11-23",
      "time": "11:42 PM",
      "label": "11:42 PM, Nov 23"
    },
    "ends": {
      "date": "2026-11-24",
      "time": "08:23 PM",
      "label": "08:23 PM, Nov 24"
    }
  },
  {
    "date": "2026-12-08",
    "kind": "amavasya",
    "begins": {
      "date": "2026-12-08",
      "time": "04:12 AM",
      "label": "04:12 AM, Dec 08"
    },
    "ends": {
      "date": "2026-12-09",
      "time": "06:21 AM",
      "label": "06:21 AM, Dec 09"
    }
  },
  {
    "date": "2026-12-23",
    "kind": "purnima",
    "begins": {
      "date": "2026-12-23",
      "time": "10:47 AM",
      "label": "10:47 AM, Dec 23"
    },
    "ends": {
      "date": "2026-12-24",
      "time": "06:57 AM",
      "label": "06:57 AM, Dec 24"
    }
  }
];

export const lunarDays2027: LunarDay[] = [
  {
    "date": "2027-01-07",
    "kind": "amavasya",
    "begins": {
      "date": "2027-01-06",
      "time": "11:13 PM",
      "label": "11:13 PM, Jan 06"
    },
    "ends": {
      "date": "2027-01-08",
      "time": "01:53 AM",
      "label": "01:53 AM, Jan 08"
    }
  },
  {
    "date": "2027-01-22",
    "kind": "purnima",
    "begins": {
      "date": "2027-01-21",
      "time": "09:29 PM",
      "label": "09:29 PM, Jan 21"
    },
    "ends": {
      "date": "2027-01-22",
      "time": "05:46 PM",
      "label": "05:46 PM, Jan 22"
    }
  },
  {
    "date": "2027-02-06",
    "kind": "amavasya",
    "begins": {
      "date": "2027-02-05",
      "time": "07:05 PM",
      "label": "07:05 PM, Feb 05"
    },
    "ends": {
      "date": "2027-02-06",
      "time": "09:25 PM",
      "label": "09:25 PM, Feb 06"
    }
  },
  {
    "date": "2027-02-20",
    "kind": "purnima",
    "begins": {
      "date": "2027-02-20",
      "time": "07:59 AM",
      "label": "07:59 AM, Feb 20"
    },
    "ends": {
      "date": "2027-02-21",
      "time": "04:52 AM",
      "label": "04:52 AM, Feb 21"
    }
  },
  {
    "date": "2027-03-07",
    "kind": "amavasya",
    "begins": {
      "date": "2027-03-07",
      "time": "01:46 PM",
      "label": "01:46 PM, Mar 07"
    },
    "ends": {
      "date": "2027-03-08",
      "time": "02:58 PM",
      "label": "02:58 PM, Mar 08"
    }
  },
  {
    "date": "2027-03-22",
    "kind": "purnima",
    "begins": {
      "date": "2027-03-21",
      "time": "06:21 PM",
      "label": "06:21 PM, Mar 21"
    },
    "ends": {
      "date": "2027-03-22",
      "time": "04:13 PM",
      "label": "04:13 PM, Mar 22"
    }
  },
  {
    "date": "2027-04-06",
    "kind": "amavasya",
    "begins": {
      "date": "2027-04-06",
      "time": "05:40 AM",
      "label": "05:40 AM, Apr 06"
    },
    "ends": {
      "date": "2027-04-07",
      "time": "05:20 AM",
      "label": "05:20 AM, Apr 07"
    }
  },
  {
    "date": "2027-04-20",
    "kind": "purnima",
    "begins": {
      "date": "2027-04-20",
      "time": "04:51 AM",
      "label": "04:51 AM, Apr 20"
    },
    "ends": {
      "date": "2027-04-21",
      "time": "03:56 AM",
      "label": "03:56 AM, Apr 21"
    }
  },
  {
    "date": "2027-05-06",
    "kind": "amavasya",
    "begins": {
      "date": "2027-05-05",
      "time": "06:16 PM",
      "label": "06:16 PM, May 05"
    },
    "ends": {
      "date": "2027-05-06",
      "time": "04:27 PM",
      "label": "04:27 PM, May 06"
    }
  },
  {
    "date": "2027-05-20",
    "kind": "purnima",
    "begins": {
      "date": "2027-05-19",
      "time": "04:02 PM",
      "label": "04:02 PM, May 19"
    },
    "ends": {
      "date": "2027-05-20",
      "time": "04:28 PM",
      "label": "04:28 PM, May 20"
    }
  },
  {
    "date": "2027-06-04",
    "kind": "amavasya",
    "begins": {
      "date": "2027-06-04",
      "time": "04:05 AM",
      "label": "04:05 AM, Jun 04"
    },
    "ends": {
      "date": "2027-06-05",
      "time": "01:09 AM",
      "label": "01:09 AM, Jun 05"
    }
  },
  {
    "date": "2027-06-18",
    "kind": "purnima",
    "begins": {
      "date": "2027-06-18",
      "time": "04:34 AM",
      "label": "04:34 AM, Jun 18"
    },
    "ends": {
      "date": "2027-06-19",
      "time": "06:13 AM",
      "label": "06:13 AM, Jun 19"
    }
  },
  {
    "date": "2027-07-03",
    "kind": "amavasya",
    "begins": {
      "date": "2027-07-03",
      "time": "12:05 PM",
      "label": "12:05 PM, Jul 03"
    },
    "ends": {
      "date": "2027-07-04",
      "time": "08:31 AM",
      "label": "08:31 AM, Jul 04"
    }
  },
  {
    "date": "2027-07-18",
    "kind": "purnima",
    "begins": {
      "date": "2027-07-17",
      "time": "06:48 PM",
      "label": "06:48 PM, Jul 17"
    },
    "ends": {
      "date": "2027-07-18",
      "time": "09:14 PM",
      "label": "09:14 PM, Jul 18"
    }
  },
  {
    "date": "2027-08-02",
    "kind": "amavasya",
    "begins": {
      "date": "2027-08-01",
      "time": "07:19 PM",
      "label": "07:19 PM, Aug 01"
    },
    "ends": {
      "date": "2027-08-02",
      "time": "03:34 PM",
      "label": "03:34 PM, Aug 02"
    }
  },
  {
    "date": "2027-08-17",
    "kind": "purnima",
    "begins": {
      "date": "2027-08-16",
      "time": "10:28 AM",
      "label": "10:28 AM, Aug 16"
    },
    "ends": {
      "date": "2027-08-17",
      "time": "12:58 PM",
      "label": "12:58 PM, Aug 17"
    }
  },
  {
    "date": "2027-08-31",
    "kind": "amavasya",
    "begins": {
      "date": "2027-08-31",
      "time": "02:40 AM",
      "label": "02:40 AM, Aug 31"
    },
    "ends": {
      "date": "2027-08-31",
      "time": "11:10 PM",
      "label": "11:10 PM, Aug 31"
    }
  },
  {
    "date": "2027-09-15",
    "kind": "purnima",
    "begins": {
      "date": "2027-09-15",
      "time": "02:48 AM",
      "label": "02:48 AM, Sep 15"
    },
    "ends": {
      "date": "2027-09-16",
      "time": "04:32 AM",
      "label": "04:32 AM, Sep 16"
    }
  },
  {
    "date": "2027-09-29",
    "kind": "amavasya",
    "begins": {
      "date": "2027-09-29",
      "time": "10:54 AM",
      "label": "10:54 AM, Sep 29"
    },
    "ends": {
      "date": "2027-09-30",
      "time": "08:05 AM",
      "label": "08:05 AM, Sep 30"
    }
  },
  {
    "date": "2027-10-15",
    "kind": "purnima",
    "begins": {
      "date": "2027-10-14",
      "time": "06:49 PM",
      "label": "06:49 PM, Oct 14"
    },
    "ends": {
      "date": "2027-10-15",
      "time": "07:16 PM",
      "label": "07:16 PM, Oct 15"
    }
  },
  {
    "date": "2027-10-29",
    "kind": "amavasya",
    "begins": {
      "date": "2027-10-28",
      "time": "08:47 PM",
      "label": "08:47 PM, Oct 28"
    },
    "ends": {
      "date": "2027-10-29",
      "time": "07:05 PM",
      "label": "07:05 PM, Oct 29"
    }
  },
  {
    "date": "2027-11-14",
    "kind": "purnima",
    "begins": {
      "date": "2027-11-13",
      "time": "09:55 AM",
      "label": "09:55 AM, Nov 13"
    },
    "ends": {
      "date": "2027-11-14",
      "time": "08:55 AM",
      "label": "08:55 AM, Nov 14"
    }
  },
  {
    "date": "2027-11-27",
    "kind": "amavasya",
    "begins": {
      "date": "2027-11-27",
      "time": "09:07 AM",
      "label": "09:07 AM, Nov 27"
    },
    "ends": {
      "date": "2027-11-28",
      "time": "08:53 AM",
      "label": "08:53 AM, Nov 28"
    }
  },
  {
    "date": "2027-12-13",
    "kind": "purnima",
    "begins": {
      "date": "2027-12-12",
      "time": "11:54 PM",
      "label": "11:54 PM, Dec 12"
    },
    "ends": {
      "date": "2027-12-13",
      "time": "09:38 PM",
      "label": "09:38 PM, Dec 13"
    }
  },
  {
    "date": "2027-12-27",
    "kind": "amavasya",
    "begins": {
      "date": "2027-12-27",
      "time": "12:22 AM",
      "label": "12:22 AM, Dec 27"
    },
    "ends": {
      "date": "2027-12-28",
      "time": "01:41 AM",
      "label": "01:41 AM, Dec 28"
    }
  }
];

export const lunarDays2028: LunarDay[] = [
  {
    "date": "2028-01-12",
    "kind": "purnima",
    "begins": {
      "date": "2028-01-11",
      "time": "12:45 PM",
      "label": "12:45 PM, Jan 11"
    },
    "ends": {
      "date": "2028-01-12",
      "time": "09:32 AM",
      "label": "09:32 AM, Jan 12"
    }
  },
  {
    "date": "2028-01-26",
    "kind": "amavasya",
    "begins": {
      "date": "2028-01-25",
      "time": "06:16 PM",
      "label": "06:16 PM, Jan 25"
    },
    "ends": {
      "date": "2028-01-26",
      "time": "08:41 PM",
      "label": "08:41 PM, Jan 26"
    }
  },
  {
    "date": "2028-02-10",
    "kind": "purnima",
    "begins": {
      "date": "2028-02-10",
      "time": "12:16 AM",
      "label": "12:16 AM, Feb 10"
    },
    "ends": {
      "date": "2028-02-10",
      "time": "08:32 PM",
      "label": "08:32 PM, Feb 10"
    }
  },
  {
    "date": "2028-02-24",
    "kind": "amavasya",
    "begins": {
      "date": "2028-02-24",
      "time": "01:26 PM",
      "label": "01:26 PM, Feb 24"
    },
    "ends": {
      "date": "2028-02-25",
      "time": "04:06 PM",
      "label": "04:06 PM, Feb 25"
    }
  },
  {
    "date": "2028-03-10",
    "kind": "purnima",
    "begins": {
      "date": "2028-03-10",
      "time": "10:20 AM",
      "label": "10:20 AM, Mar 10"
    },
    "ends": {
      "date": "2028-03-11",
      "time": "06:35 AM",
      "label": "06:35 AM, Mar 11"
    }
  },
  {
    "date": "2028-03-25",
    "kind": "amavasya",
    "begins": {
      "date": "2028-03-25",
      "time": "07:56 AM",
      "label": "07:56 AM, Mar 25"
    },
    "ends": {
      "date": "2028-03-26",
      "time": "10:00 AM",
      "label": "10:00 AM, Mar 26"
    }
  },
  {
    "date": "2028-04-09",
    "kind": "purnima",
    "begins": {
      "date": "2028-04-08",
      "time": "07:10 PM",
      "label": "07:10 PM, Apr 08"
    },
    "ends": {
      "date": "2028-04-09",
      "time": "03:55 PM",
      "label": "03:55 PM, Apr 09"
    }
  },
  {
    "date": "2028-04-24",
    "kind": "amavasya",
    "begins": {
      "date": "2028-04-24",
      "time": "12:20 AM",
      "label": "12:20 AM, Apr 24"
    },
    "ends": {
      "date": "2028-04-25",
      "time": "01:16 AM",
      "label": "01:16 AM, Apr 25"
    }
  },
  {
    "date": "2028-05-08",
    "kind": "purnima",
    "begins": {
      "date": "2028-05-08",
      "time": "03:32 AM",
      "label": "03:32 AM, May 08"
    },
    "ends": {
      "date": "2028-05-09",
      "time": "01:18 AM",
      "label": "01:18 AM, May 09"
    }
  },
  {
    "date": "2028-05-23",
    "kind": "amavasya",
    "begins": {
      "date": "2028-05-23",
      "time": "02:09 PM",
      "label": "02:09 PM, May 23"
    },
    "ends": {
      "date": "2028-05-24",
      "time": "01:45 PM",
      "label": "01:45 PM, May 24"
    }
  },
  {
    "date": "2028-06-07",
    "kind": "purnima",
    "begins": {
      "date": "2028-06-06",
      "time": "12:29 PM",
      "label": "12:29 PM, Jun 06"
    },
    "ends": {
      "date": "2028-06-07",
      "time": "11:38 AM",
      "label": "11:38 AM, Jun 07"
    }
  },
  {
    "date": "2028-06-22",
    "kind": "amavasya",
    "begins": {
      "date": "2028-06-22",
      "time": "01:37 AM",
      "label": "01:37 AM, Jun 22"
    },
    "ends": {
      "date": "2028-06-22",
      "time": "11:56 PM",
      "label": "11:56 PM, Jun 22"
    }
  },
  {
    "date": "2028-07-06",
    "kind": "purnima",
    "begins": {
      "date": "2028-07-05",
      "time": "11:03 PM",
      "label": "11:03 PM, Jul 05"
    },
    "ends": {
      "date": "2028-07-06",
      "time": "11:40 PM",
      "label": "11:40 PM, Jul 06"
    }
  },
  {
    "date": "2028-07-21",
    "kind": "amavasya",
    "begins": {
      "date": "2028-07-21",
      "time": "11:17 AM",
      "label": "11:17 AM, Jul 21"
    },
    "ends": {
      "date": "2028-07-22",
      "time": "08:30 AM",
      "label": "08:30 AM, Jul 22"
    }
  },
  {
    "date": "2028-08-05",
    "kind": "purnima",
    "begins": {
      "date": "2028-08-04",
      "time": "11:51 AM",
      "label": "11:51 AM, Aug 04"
    },
    "ends": {
      "date": "2028-08-05",
      "time": "01:39 PM",
      "label": "01:39 PM, Aug 05"
    }
  },
  {
    "date": "2028-08-20",
    "kind": "amavasya",
    "begins": {
      "date": "2028-08-19",
      "time": "07:46 PM",
      "label": "07:46 PM, Aug 19"
    },
    "ends": {
      "date": "2028-08-20",
      "time": "04:13 PM",
      "label": "04:13 PM, Aug 20"
    }
  },
  {
    "date": "2028-09-03",
    "kind": "purnima",
    "begins": {
      "date": "2028-09-03",
      "time": "02:51 AM",
      "label": "02:51 AM, Sep 03"
    },
    "ends": {
      "date": "2028-09-04",
      "time": "05:16 AM",
      "label": "05:16 AM, Sep 04"
    }
  },
  {
    "date": "2028-09-18",
    "kind": "amavasya",
    "begins": {
      "date": "2028-09-18",
      "time": "03:46 AM",
      "label": "03:46 AM, Sep 18"
    },
    "ends": {
      "date": "2028-09-18",
      "time": "11:53 PM",
      "label": "11:53 PM, Sep 18"
    }
  },
  {
    "date": "2028-10-03",
    "kind": "purnima",
    "begins": {
      "date": "2028-10-02",
      "time": "07:33 PM",
      "label": "07:33 PM, Oct 02"
    },
    "ends": {
      "date": "2028-10-03",
      "time": "09:54 PM",
      "label": "09:54 PM, Oct 03"
    }
  },
  {
    "date": "2028-10-17",
    "kind": "amavasya",
    "begins": {
      "date": "2028-10-17",
      "time": "12:04 PM",
      "label": "12:04 PM, Oct 17"
    },
    "ends": {
      "date": "2028-10-18",
      "time": "08:26 AM",
      "label": "08:26 AM, Oct 18"
    }
  },
  {
    "date": "2028-11-02",
    "kind": "purnima",
    "begins": {
      "date": "2028-11-01",
      "time": "01:07 PM",
      "label": "01:07 PM, Nov 01"
    },
    "ends": {
      "date": "2028-11-02",
      "time": "02:46 PM",
      "label": "02:46 PM, Nov 02"
    }
  },
  {
    "date": "2028-11-16",
    "kind": "amavasya",
    "begins": {
      "date": "2028-11-15",
      "time": "09:34 PM",
      "label": "09:34 PM, Nov 15"
    },
    "ends": {
      "date": "2028-11-16",
      "time": "06:47 PM",
      "label": "06:47 PM, Nov 16"
    }
  },
  {
    "date": "2028-12-01",
    "kind": "purnima",
    "begins": {
      "date": "2028-12-01",
      "time": "06:40 AM",
      "label": "06:40 AM, Dec 01"
    },
    "ends": {
      "date": "2028-12-02",
      "time": "07:09 AM",
      "label": "07:09 AM, Dec 02"
    }
  },
  {
    "date": "2028-12-15",
    "kind": "amavasya",
    "begins": {
      "date": "2028-12-15",
      "time": "09:00 AM",
      "label": "09:00 AM, Dec 15"
    },
    "ends": {
      "date": "2028-12-16",
      "time": "07:35 AM",
      "label": "07:35 AM, Dec 16"
    }
  },
  {
    "date": "2028-12-31",
    "kind": "purnima",
    "begins": {
      "date": "2028-12-30",
      "time": "11:13 PM",
      "label": "11:13 PM, Dec 30"
    },
    "ends": {
      "date": "2028-12-31",
      "time": "10:17 PM",
      "label": "10:17 PM, Dec 31"
    }
  }
];

export const lunarDays2029: LunarDay[] = [
  {
    "date": "2029-01-14",
    "kind": "amavasya",
    "begins": {
      "date": "2029-01-13",
      "time": "10:46 PM",
      "label": "10:46 PM, Jan 13"
    },
    "ends": {
      "date": "2029-01-14",
      "time": "10:53 PM",
      "label": "10:53 PM, Jan 14"
    }
  },
  {
    "date": "2029-01-30",
    "kind": "purnima",
    "begins": {
      "date": "2029-01-29",
      "time": "01:53 PM",
      "label": "01:53 PM, Jan 29"
    },
    "ends": {
      "date": "2029-01-30",
      "time": "11:32 AM",
      "label": "11:32 AM, Jan 30"
    }
  },
  {
    "date": "2029-02-13",
    "kind": "amavasya",
    "begins": {
      "date": "2029-02-12",
      "time": "02:34 PM",
      "label": "02:34 PM, Feb 12"
    },
    "ends": {
      "date": "2029-02-13",
      "time": "04:00 PM",
      "label": "04:00 PM, Feb 13"
    }
  },
  {
    "date": "2029-02-28",
    "kind": "purnima",
    "begins": {
      "date": "2029-02-28",
      "time": "02:04 AM",
      "label": "02:04 AM, Feb 28"
    },
    "ends": {
      "date": "2029-02-28",
      "time": "10:39 PM",
      "label": "10:39 PM, Feb 28"
    }
  },
  {
    "date": "2029-03-14",
    "kind": "amavasya",
    "begins": {
      "date": "2029-03-14",
      "time": "07:33 AM",
      "label": "07:33 AM, Mar 14"
    },
    "ends": {
      "date": "2029-03-15",
      "time": "09:48 AM",
      "label": "09:48 AM, Mar 15"
    }
  },
  {
    "date": "2029-03-30",
    "kind": "purnima",
    "begins": {
      "date": "2029-03-29",
      "time": "11:51 AM",
      "label": "11:51 AM, Mar 29"
    },
    "ends": {
      "date": "2029-03-30",
      "time": "07:55 AM",
      "label": "07:55 AM, Mar 30"
    }
  },
  {
    "date": "2029-04-13",
    "kind": "amavasya",
    "begins": {
      "date": "2029-04-13",
      "time": "12:42 AM",
      "label": "12:42 AM, Apr 13"
    },
    "ends": {
      "date": "2029-04-14",
      "time": "03:09 AM",
      "label": "03:09 AM, Apr 14"
    }
  },
  {
    "date": "2029-04-28",
    "kind": "purnima",
    "begins": {
      "date": "2029-04-27",
      "time": "07:55 PM",
      "label": "07:55 PM, Apr 27"
    },
    "ends": {
      "date": "2029-04-28",
      "time": "04:06 PM",
      "label": "04:06 PM, Apr 28"
    }
  },
  {
    "date": "2029-05-13",
    "kind": "amavasya",
    "begins": {
      "date": "2029-05-12",
      "time": "05:09 PM",
      "label": "05:09 PM, May 12"
    },
    "ends": {
      "date": "2029-05-13",
      "time": "07:11 PM",
      "label": "07:11 PM, May 13"
    }
  },
  {
    "date": "2029-05-27",
    "kind": "purnima",
    "begins": {
      "date": "2029-05-27",
      "time": "03:14 AM",
      "label": "03:14 AM, May 27"
    },
    "ends": {
      "date": "2029-05-28",
      "time": "12:06 AM",
      "label": "12:06 AM, May 28"
    }
  },
  {
    "date": "2029-06-11",
    "kind": "amavasya",
    "begins": {
      "date": "2029-06-11",
      "time": "08:17 AM",
      "label": "08:17 AM, Jun 11"
    },
    "ends": {
      "date": "2029-06-12",
      "time": "09:19 AM",
      "label": "09:19 AM, Jun 12"
    }
  },
  {
    "date": "2029-06-26",
    "kind": "purnima",
    "begins": {
      "date": "2029-06-25",
      "time": "10:54 AM",
      "label": "10:54 AM, Jun 25"
    },
    "ends": {
      "date": "2029-06-26",
      "time": "08:51 AM",
      "label": "08:51 AM, Jun 26"
    }
  },
  {
    "date": "2029-07-11",
    "kind": "amavasya",
    "begins": {
      "date": "2029-07-10",
      "time": "09:39 PM",
      "label": "09:39 PM, Jul 10"
    },
    "ends": {
      "date": "2029-07-11",
      "time": "09:20 PM",
      "label": "09:20 PM, Jul 11"
    }
  },
  {
    "date": "2029-07-25",
    "kind": "purnima",
    "begins": {
      "date": "2029-07-24",
      "time": "07:50 PM",
      "label": "07:50 PM, Jul 24"
    },
    "ends": {
      "date": "2029-07-25",
      "time": "07:05 PM",
      "label": "07:05 PM, Jul 25"
    }
  },
  {
    "date": "2029-08-09",
    "kind": "amavasya",
    "begins": {
      "date": "2029-08-09",
      "time": "09:10 AM",
      "label": "09:10 AM, Aug 09"
    },
    "ends": {
      "date": "2029-08-10",
      "time": "07:25 AM",
      "label": "07:25 AM, Aug 10"
    }
  },
  {
    "date": "2029-08-24",
    "kind": "purnima",
    "begins": {
      "date": "2029-08-23",
      "time": "06:47 AM",
      "label": "06:47 AM, Aug 23"
    },
    "ends": {
      "date": "2029-08-24",
      "time": "07:20 AM",
      "label": "07:20 AM, Aug 24"
    }
  },
  {
    "date": "2029-09-08",
    "kind": "amavasya",
    "begins": {
      "date": "2029-09-07",
      "time": "07:11 PM",
      "label": "07:11 PM, Sep 07"
    },
    "ends": {
      "date": "2029-09-08",
      "time": "04:13 PM",
      "label": "04:13 PM, Sep 08"
    }
  },
  {
    "date": "2029-09-22",
    "kind": "purnima",
    "begins": {
      "date": "2029-09-21",
      "time": "08:17 PM",
      "label": "08:17 PM, Sep 21"
    },
    "ends": {
      "date": "2029-09-22",
      "time": "09:58 PM",
      "label": "09:58 PM, Sep 22"
    }
  },
  {
    "date": "2029-10-07",
    "kind": "amavasya",
    "begins": {
      "date": "2029-10-07",
      "time": "04:26 AM",
      "label": "04:26 AM, Oct 07"
    },
    "ends": {
      "date": "2029-10-08",
      "time": "12:43 AM",
      "label": "12:43 AM, Oct 08"
    }
  },
  {
    "date": "2029-10-22",
    "kind": "purnima",
    "begins": {
      "date": "2029-10-21",
      "time": "12:31 PM",
      "label": "12:31 PM, Oct 21"
    },
    "ends": {
      "date": "2029-10-22",
      "time": "02:56 PM",
      "label": "02:56 PM, Oct 22"
    }
  },
  {
    "date": "2029-11-05",
    "kind": "amavasya",
    "begins": {
      "date": "2029-11-05",
      "time": "01:44 PM",
      "label": "01:44 PM, Nov 05"
    },
    "ends": {
      "date": "2029-11-06",
      "time": "09:53 AM",
      "label": "09:53 AM, Nov 06"
    }
  },
  {
    "date": "2029-11-21",
    "kind": "purnima",
    "begins": {
      "date": "2029-11-20",
      "time": "07:01 AM",
      "label": "07:01 AM, Nov 20"
    },
    "ends": {
      "date": "2029-11-21",
      "time": "09:32 AM",
      "label": "09:32 AM, Nov 21"
    }
  },
  {
    "date": "2029-12-05",
    "kind": "amavasya",
    "begins": {
      "date": "2029-12-04",
      "time": "11:46 PM",
      "label": "11:46 PM, Dec 04"
    },
    "ends": {
      "date": "2029-12-05",
      "time": "08:21 PM",
      "label": "08:21 PM, Dec 05"
    }
  },
  {
    "date": "2029-12-20",
    "kind": "purnima",
    "begins": {
      "date": "2029-12-20",
      "time": "02:29 AM",
      "label": "02:29 AM, Dec 20"
    },
    "ends": {
      "date": "2029-12-21",
      "time": "04:15 AM",
      "label": "04:15 AM, Dec 21"
    }
  }
];

export const lunarDays2030: LunarDay[] = [
  {
    "date": "2030-01-03",
    "kind": "amavasya",
    "begins": {
      "date": "2030-01-03",
      "time": "10:49 AM",
      "label": "10:49 AM, Jan 03"
    },
    "ends": {
      "date": "2030-01-04",
      "time": "08:18 AM",
      "label": "08:18 AM, Jan 04"
    }
  },
  {
    "date": "2030-01-19",
    "kind": "purnima",
    "begins": {
      "date": "2030-01-18",
      "time": "09:02 PM",
      "label": "09:02 PM, Jan 18"
    },
    "ends": {
      "date": "2030-01-19",
      "time": "09:23 PM",
      "label": "09:23 PM, Jan 19"
    }
  },
  {
    "date": "2030-02-02",
    "kind": "amavasya",
    "begins": {
      "date": "2030-02-01",
      "time": "10:55 PM",
      "label": "10:55 PM, Feb 01"
    },
    "ends": {
      "date": "2030-02-02",
      "time": "09:36 PM",
      "label": "09:36 PM, Feb 02"
    }
  },
  {
    "date": "2030-02-18",
    "kind": "purnima",
    "begins": {
      "date": "2030-02-17",
      "time": "01:04 PM",
      "label": "01:04 PM, Feb 17"
    },
    "ends": {
      "date": "2030-02-18",
      "time": "11:49 AM",
      "label": "11:49 AM, Feb 18"
    }
  },
  {
    "date": "2030-03-03",
    "kind": "amavasya",
    "begins": {
      "date": "2030-03-03",
      "time": "12:01 PM",
      "label": "12:01 PM, Mar 03"
    },
    "ends": {
      "date": "2030-03-04",
      "time": "12:04 PM",
      "label": "12:04 PM, Mar 04"
    }
  },
  {
    "date": "2030-03-19",
    "kind": "purnima",
    "begins": {
      "date": "2030-03-19",
      "time": "02:02 AM",
      "label": "02:02 AM, Mar 19"
    },
    "ends": {
      "date": "2030-03-19",
      "time": "11:25 PM",
      "label": "11:25 PM, Mar 19"
    }
  },
  {
    "date": "2030-04-02",
    "kind": "amavasya",
    "begins": {
      "date": "2030-04-02",
      "time": "02:10 AM",
      "label": "02:10 AM, Apr 02"
    },
    "ends": {
      "date": "2030-04-03",
      "time": "03:31 AM",
      "label": "03:31 AM, Apr 03"
    }
  },
  {
    "date": "2030-04-18",
    "kind": "purnima",
    "begins": {
      "date": "2030-04-17",
      "time": "12:17 PM",
      "label": "12:17 PM, Apr 17"
    },
    "ends": {
      "date": "2030-04-18",
      "time": "08:49 AM",
      "label": "08:49 AM, Apr 18"
    }
  },
  {
    "date": "2030-05-02",
    "kind": "amavasya",
    "begins": {
      "date": "2030-05-01",
      "time": "05:23 PM",
      "label": "05:23 PM, May 01"
    },
    "ends": {
      "date": "2030-05-02",
      "time": "07:41 PM",
      "label": "07:41 PM, May 02"
    }
  },
  {
    "date": "2030-05-17",
    "kind": "purnima",
    "begins": {
      "date": "2030-05-16",
      "time": "08:36 PM",
      "label": "08:36 PM, May 16"
    },
    "ends": {
      "date": "2030-05-17",
      "time": "04:48 PM",
      "label": "04:48 PM, May 17"
    }
  },
  {
    "date": "2030-05-31",
    "kind": "amavasya",
    "begins": {
      "date": "2030-05-31",
      "time": "09:15 AM",
      "label": "09:15 AM, May 31"
    },
    "ends": {
      "date": "2030-06-01",
      "time": "11:50 AM",
      "label": "11:50 AM, Jun 01"
    }
  },
  {
    "date": "2030-06-15",
    "kind": "purnima",
    "begins": {
      "date": "2030-06-15",
      "time": "03:49 AM",
      "label": "03:49 AM, Jun 15"
    },
    "ends": {
      "date": "2030-06-16",
      "time": "12:10 AM",
      "label": "12:10 AM, Jun 16"
    }
  },
  {
    "date": "2030-06-30",
    "kind": "amavasya",
    "begins": {
      "date": "2030-06-30",
      "time": "12:59 AM",
      "label": "12:59 AM, Jun 30"
    },
    "ends": {
      "date": "2030-07-01",
      "time": "03:03 AM",
      "label": "03:03 AM, Jul 01"
    }
  },
  {
    "date": "2030-07-15",
    "kind": "purnima",
    "begins": {
      "date": "2030-07-14",
      "time": "10:47 AM",
      "label": "10:47 AM, Jul 14"
    },
    "ends": {
      "date": "2030-07-15",
      "time": "07:41 AM",
      "label": "07:41 AM, Jul 15"
    }
  },
  {
    "date": "2030-07-30",
    "kind": "amavasya",
    "begins": {
      "date": "2030-07-29",
      "time": "03:44 PM",
      "label": "03:44 PM, Jul 29"
    },
    "ends": {
      "date": "2030-07-30",
      "time": "04:40 PM",
      "label": "04:40 PM, Jul 30"
    }
  },
  {
    "date": "2030-08-13",
    "kind": "purnima",
    "begins": {
      "date": "2030-08-12",
      "time": "06:23 PM",
      "label": "06:23 PM, Aug 12"
    },
    "ends": {
      "date": "2030-08-13",
      "time": "04:13 PM",
      "label": "04:13 PM, Aug 13"
    }
  },
  {
    "date": "2030-08-28",
    "kind": "amavasya",
    "begins": {
      "date": "2030-08-28",
      "time": "05:06 AM",
      "label": "05:06 AM, Aug 28"
    },
    "ends": {
      "date": "2030-08-29",
      "time": "04:36 AM",
      "label": "04:36 AM, Aug 29"
    }
  },
  {
    "date": "2030-09-11",
    "kind": "purnima",
    "begins": {
      "date": "2030-09-11",
      "time": "03:39 AM",
      "label": "03:39 AM, Sep 11"
    },
    "ends": {
      "date": "2030-09-12",
      "time": "02:47 AM",
      "label": "02:47 AM, Sep 12"
    }
  },
  {
    "date": "2030-09-27",
    "kind": "amavasya",
    "begins": {
      "date": "2030-09-26",
      "time": "05:15 PM",
      "label": "05:15 PM, Sep 26"
    },
    "ends": {
      "date": "2030-09-27",
      "time": "03:23 PM",
      "label": "03:23 PM, Sep 27"
    }
  },
  {
    "date": "2030-10-11",
    "kind": "purnima",
    "begins": {
      "date": "2030-10-10",
      "time": "03:39 PM",
      "label": "03:39 PM, Oct 10"
    },
    "ends": {
      "date": "2030-10-11",
      "time": "04:16 PM",
      "label": "04:16 PM, Oct 11"
    }
  },
  {
    "date": "2030-10-26",
    "kind": "amavasya",
    "begins": {
      "date": "2030-10-26",
      "time": "04:40 AM",
      "label": "04:40 AM, Oct 26"
    },
    "ends": {
      "date": "2030-10-27",
      "time": "01:46 AM",
      "label": "01:46 AM, Oct 27"
    }
  },
  {
    "date": "2030-11-10",
    "kind": "purnima",
    "begins": {
      "date": "2030-11-09",
      "time": "07:02 AM",
      "label": "07:02 AM, Nov 09"
    },
    "ends": {
      "date": "2030-11-10",
      "time": "08:59 AM",
      "label": "08:59 AM, Nov 10"
    }
  },
  {
    "date": "2030-11-24",
    "kind": "amavasya",
    "begins": {
      "date": "2030-11-24",
      "time": "03:49 PM",
      "label": "03:49 PM, Nov 24"
    },
    "ends": {
      "date": "2030-11-25",
      "time": "12:15 PM",
      "label": "12:15 PM, Nov 25"
    }
  },
  {
    "date": "2030-12-09",
    "kind": "purnima",
    "begins": {
      "date": "2030-12-09",
      "time": "01:29 AM",
      "label": "01:29 AM, Dec 09"
    },
    "ends": {
      "date": "2030-12-10",
      "time": "04:09 AM",
      "label": "04:09 AM, Dec 10"
    }
  },
  {
    "date": "2030-12-24",
    "kind": "amavasya",
    "begins": {
      "date": "2030-12-24",
      "time": "02:46 AM",
      "label": "02:46 AM, Dec 24"
    },
    "ends": {
      "date": "2030-12-24",
      "time": "11:01 PM",
      "label": "11:01 PM, Dec 24"
    }
  }
];

export const lunarDays2031: LunarDay[] = [
  {
    "date": "2031-01-08",
    "kind": "purnima",
    "begins": {
      "date": "2031-01-07",
      "time": "09:27 PM",
      "label": "09:27 PM, Jan 07"
    },
    "ends": {
      "date": "2031-01-08",
      "time": "11:55 PM",
      "label": "11:55 PM, Jan 08"
    }
  },
  {
    "date": "2031-01-22",
    "kind": "amavasya",
    "begins": {
      "date": "2031-01-22",
      "time": "01:26 PM",
      "label": "01:26 PM, Jan 22"
    },
    "ends": {
      "date": "2031-01-23",
      "time": "10:00 AM",
      "label": "10:00 AM, Jan 23"
    }
  },
  {
    "date": "2031-02-07",
    "kind": "purnima",
    "begins": {
      "date": "2031-02-06",
      "time": "04:48 PM",
      "label": "04:48 PM, Feb 06"
    },
    "ends": {
      "date": "2031-02-07",
      "time": "06:15 PM",
      "label": "06:15 PM, Feb 07"
    }
  },
  {
    "date": "2031-02-21",
    "kind": "amavasya",
    "begins": {
      "date": "2031-02-20",
      "time": "11:54 PM",
      "label": "11:54 PM, Feb 20"
    },
    "ends": {
      "date": "2031-02-21",
      "time": "09:18 PM",
      "label": "09:18 PM, Feb 21"
    }
  },
  {
    "date": "2031-03-09",
    "kind": "purnima",
    "begins": {
      "date": "2031-03-08",
      "time": "09:54 AM",
      "label": "09:54 AM, Mar 08"
    },
    "ends": {
      "date": "2031-03-09",
      "time": "09:58 AM",
      "label": "09:58 AM, Mar 09"
    }
  },
  {
    "date": "2031-03-22",
    "kind": "amavasya",
    "begins": {
      "date": "2031-03-22",
      "time": "10:37 AM",
      "label": "10:37 AM, Mar 22"
    },
    "ends": {
      "date": "2031-03-23",
      "time": "09:18 AM",
      "label": "09:18 AM, Mar 23"
    }
  },
  {
    "date": "2031-04-07",
    "kind": "purnima",
    "begins": {
      "date": "2031-04-07",
      "time": "12:09 AM",
      "label": "12:09 AM, Apr 07"
    },
    "ends": {
      "date": "2031-04-07",
      "time": "10:50 PM",
      "label": "10:50 PM, Apr 07"
    }
  },
  {
    "date": "2031-04-21",
    "kind": "amavasya",
    "begins": {
      "date": "2031-04-20",
      "time": "10:14 PM",
      "label": "10:14 PM, Apr 20"
    },
    "ends": {
      "date": "2031-04-21",
      "time": "10:26 PM",
      "label": "10:26 PM, Apr 21"
    }
  },
  {
    "date": "2031-05-07",
    "kind": "purnima",
    "begins": {
      "date": "2031-05-06",
      "time": "11:39 AM",
      "label": "11:39 AM, May 06"
    },
    "ends": {
      "date": "2031-05-07",
      "time": "09:09 AM",
      "label": "09:09 AM, May 07"
    }
  },
  {
    "date": "2031-05-20",
    "kind": "amavasya",
    "begins": {
      "date": "2031-05-20",
      "time": "11:14 AM",
      "label": "11:14 AM, May 20"
    },
    "ends": {
      "date": "2031-05-21",
      "time": "12:46 PM",
      "label": "12:46 PM, May 21"
    }
  },
  {
    "date": "2031-06-05",
    "kind": "purnima",
    "begins": {
      "date": "2031-06-04",
      "time": "08:50 PM",
      "label": "08:50 PM, Jun 04"
    },
    "ends": {
      "date": "2031-06-05",
      "time": "05:27 PM",
      "label": "05:27 PM, Jun 05"
    }
  },
  {
    "date": "2031-06-19",
    "kind": "amavasya",
    "begins": {
      "date": "2031-06-19",
      "time": "01:33 AM",
      "label": "01:33 AM, Jun 19"
    },
    "ends": {
      "date": "2031-06-20",
      "time": "03:54 AM",
      "label": "03:54 AM, Jun 20"
    }
  },
  {
    "date": "2031-07-04",
    "kind": "purnima",
    "begins": {
      "date": "2031-07-04",
      "time": "04:21 AM",
      "label": "04:21 AM, Jul 04"
    },
    "ends": {
      "date": "2031-07-05",
      "time": "12:30 AM",
      "label": "12:30 AM, Jul 05"
    }
  },
  {
    "date": "2031-07-19",
    "kind": "amavasya",
    "begins": {
      "date": "2031-07-18",
      "time": "04:42 PM",
      "label": "04:42 PM, Jul 18"
    },
    "ends": {
      "date": "2031-07-19",
      "time": "07:09 PM",
      "label": "07:09 PM, Jul 19"
    }
  },
  {
    "date": "2031-08-03",
    "kind": "purnima",
    "begins": {
      "date": "2031-08-02",
      "time": "11:03 AM",
      "label": "11:03 AM, Aug 02"
    },
    "ends": {
      "date": "2031-08-03",
      "time": "07:14 AM",
      "label": "07:14 AM, Aug 03"
    }
  },
  {
    "date": "2031-08-17",
    "kind": "amavasya",
    "begins": {
      "date": "2031-08-17",
      "time": "08:07 AM",
      "label": "08:07 AM, Aug 17"
    },
    "ends": {
      "date": "2031-08-18",
      "time": "10:01 AM",
      "label": "10:01 AM, Aug 18"
    }
  },
  {
    "date": "2031-09-01",
    "kind": "purnima",
    "begins": {
      "date": "2031-08-31",
      "time": "06:03 PM",
      "label": "06:03 PM, Aug 31"
    },
    "ends": {
      "date": "2031-09-01",
      "time": "02:49 PM",
      "label": "02:49 PM, Sep 01"
    }
  },
  {
    "date": "2031-09-16",
    "kind": "amavasya",
    "begins": {
      "date": "2031-09-15",
      "time": "11:22 PM",
      "label": "11:22 PM, Sep 15"
    },
    "ends": {
      "date": "2031-09-17",
      "time": "12:16 AM",
      "label": "12:16 AM, Sep 17"
    }
  },
  {
    "date": "2031-09-30",
    "kind": "purnima",
    "begins": {
      "date": "2031-09-30",
      "time": "02:32 AM",
      "label": "02:32 AM, Sep 30"
    },
    "ends": {
      "date": "2031-10-01",
      "time": "12:27 AM",
      "label": "12:27 AM, Oct 01"
    }
  },
  {
    "date": "2031-10-15",
    "kind": "amavasya",
    "begins": {
      "date": "2031-10-15",
      "time": "02:13 PM",
      "label": "02:13 PM, Oct 15"
    },
    "ends": {
      "date": "2031-10-16",
      "time": "01:50 PM",
      "label": "01:50 PM, Oct 16"
    }
  },
  {
    "date": "2031-10-30",
    "kind": "purnima",
    "begins": {
      "date": "2031-10-29",
      "time": "01:37 PM",
      "label": "01:37 PM, Oct 29"
    },
    "ends": {
      "date": "2031-10-30",
      "time": "01:02 PM",
      "label": "01:02 PM, Oct 30"
    }
  },
  {
    "date": "2031-11-14",
    "kind": "amavasya",
    "begins": {
      "date": "2031-11-14",
      "time": "04:23 AM",
      "label": "04:23 AM, Nov 14"
    },
    "ends": {
      "date": "2031-11-15",
      "time": "02:38 AM",
      "label": "02:38 AM, Nov 15"
    }
  },
  {
    "date": "2031-11-28",
    "kind": "purnima",
    "begins": {
      "date": "2031-11-28",
      "time": "03:52 AM",
      "label": "03:52 AM, Nov 28"
    },
    "ends": {
      "date": "2031-11-29",
      "time": "04:47 AM",
      "label": "04:47 AM, Nov 29"
    }
  },
  {
    "date": "2031-12-14",
    "kind": "amavasya",
    "begins": {
      "date": "2031-12-13",
      "time": "05:32 PM",
      "label": "05:32 PM, Dec 13"
    },
    "ends": {
      "date": "2031-12-14",
      "time": "02:35 PM",
      "label": "02:35 PM, Dec 14"
    }
  },
  {
    "date": "2031-12-28",
    "kind": "purnima",
    "begins": {
      "date": "2031-12-27",
      "time": "08:59 PM",
      "label": "08:59 PM, Dec 27"
    },
    "ends": {
      "date": "2031-12-28",
      "time": "11:02 PM",
      "label": "11:02 PM, Dec 28"
    }
  }
];

export const lunarDays2032: LunarDay[] = [
  {
    "date": "2032-01-12",
    "kind": "amavasya",
    "begins": {
      "date": "2032-01-12",
      "time": "05:20 AM",
      "label": "05:20 AM, Jan 12"
    },
    "ends": {
      "date": "2032-01-13",
      "time": "01:35 AM",
      "label": "01:35 AM, Jan 13"
    }
  },
  {
    "date": "2032-01-27",
    "kind": "purnima",
    "begins": {
      "date": "2032-01-26",
      "time": "03:51 PM",
      "label": "03:51 PM, Jan 26"
    },
    "ends": {
      "date": "2032-01-27",
      "time": "06:21 PM",
      "label": "06:21 PM, Jan 27"
    }
  },
  {
    "date": "2032-02-10",
    "kind": "amavasya",
    "begins": {
      "date": "2032-02-10",
      "time": "03:47 PM",
      "label": "03:47 PM, Feb 10"
    },
    "ends": {
      "date": "2032-02-11",
      "time": "11:53 AM",
      "label": "11:53 AM, Feb 11"
    }
  },
  {
    "date": "2032-02-26",
    "kind": "purnima",
    "begins": {
      "date": "2032-02-25",
      "time": "10:55 AM",
      "label": "10:55 AM, Feb 25"
    },
    "ends": {
      "date": "2032-02-26",
      "time": "01:12 PM",
      "label": "01:12 PM, Feb 26"
    }
  },
  {
    "date": "2032-03-11",
    "kind": "amavasya",
    "begins": {
      "date": "2032-03-11",
      "time": "01:18 AM",
      "label": "01:18 AM, Mar 11"
    },
    "ends": {
      "date": "2032-03-11",
      "time": "09:53 PM",
      "label": "09:53 PM, Mar 11"
    }
  },
  {
    "date": "2032-03-26",
    "kind": "purnima",
    "begins": {
      "date": "2032-03-26",
      "time": "04:50 AM",
      "label": "04:50 AM, Mar 26"
    },
    "ends": {
      "date": "2032-03-27",
      "time": "06:15 AM",
      "label": "06:15 AM, Mar 27"
    }
  },
  {
    "date": "2032-04-09",
    "kind": "amavasya",
    "begins": {
      "date": "2032-04-09",
      "time": "10:32 AM",
      "label": "10:32 AM, Apr 09"
    },
    "ends": {
      "date": "2032-04-10",
      "time": "08:08 AM",
      "label": "08:08 AM, Apr 10"
    }
  },
  {
    "date": "2032-04-25",
    "kind": "purnima",
    "begins": {
      "date": "2032-04-24",
      "time": "08:30 PM",
      "label": "08:30 PM, Apr 24"
    },
    "ends": {
      "date": "2032-04-25",
      "time": "08:39 PM",
      "label": "08:39 PM, Apr 25"
    }
  },
  {
    "date": "2032-05-09",
    "kind": "amavasya",
    "begins": {
      "date": "2032-05-08",
      "time": "08:11 PM",
      "label": "08:11 PM, May 08"
    },
    "ends": {
      "date": "2032-05-09",
      "time": "07:05 PM",
      "label": "07:05 PM, May 09"
    }
  },
  {
    "date": "2032-05-25",
    "kind": "purnima",
    "begins": {
      "date": "2032-05-24",
      "time": "09:26 AM",
      "label": "09:26 AM, May 24"
    },
    "ends": {
      "date": "2032-05-25",
      "time": "08:06 AM",
      "label": "08:06 AM, May 25"
    }
  },
  {
    "date": "2032-06-07",
    "kind": "amavasya",
    "begins": {
      "date": "2032-06-07",
      "time": "06:47 AM",
      "label": "06:47 AM, Jun 07"
    },
    "ends": {
      "date": "2032-06-08",
      "time": "07:01 AM",
      "label": "07:01 AM, Jun 08"
    }
  },
  {
    "date": "2032-06-23",
    "kind": "purnima",
    "begins": {
      "date": "2032-06-22",
      "time": "07:40 PM",
      "label": "07:40 PM, Jun 22"
    },
    "ends": {
      "date": "2032-06-23",
      "time": "05:01 PM",
      "label": "05:01 PM, Jun 23"
    }
  },
  {
    "date": "2032-07-07",
    "kind": "amavasya",
    "begins": {
      "date": "2032-07-06",
      "time": "06:47 PM",
      "label": "06:47 PM, Jul 06"
    },
    "ends": {
      "date": "2032-07-07",
      "time": "08:10 PM",
      "label": "08:10 PM, Jul 07"
    }
  },
  {
    "date": "2032-07-22",
    "kind": "purnima",
    "begins": {
      "date": "2032-07-22",
      "time": "03:54 AM",
      "label": "03:54 AM, Jul 22"
    },
    "ends": {
      "date": "2032-07-23",
      "time": "12:21 AM",
      "label": "12:21 AM, Jul 23"
    }
  },
  {
    "date": "2032-08-05",
    "kind": "amavasya",
    "begins": {
      "date": "2032-08-05",
      "time": "08:29 AM",
      "label": "08:29 AM, Aug 05"
    },
    "ends": {
      "date": "2032-08-06",
      "time": "10:40 AM",
      "label": "10:40 AM, Aug 06"
    }
  },
  {
    "date": "2032-08-21",
    "kind": "purnima",
    "begins": {
      "date": "2032-08-20",
      "time": "11:12 AM",
      "label": "11:12 AM, Aug 20"
    },
    "ends": {
      "date": "2032-08-21",
      "time": "07:16 AM",
      "label": "07:16 AM, Aug 21"
    }
  },
  {
    "date": "2032-09-04",
    "kind": "amavasya",
    "begins": {
      "date": "2032-09-03",
      "time": "11:57 PM",
      "label": "11:57 PM, Sep 03"
    },
    "ends": {
      "date": "2032-09-05",
      "time": "02:26 AM",
      "label": "02:26 AM, Sep 05"
    }
  },
  {
    "date": "2032-09-19",
    "kind": "purnima",
    "begins": {
      "date": "2032-09-18",
      "time": "06:42 PM",
      "label": "06:42 PM, Sep 18"
    },
    "ends": {
      "date": "2032-09-19",
      "time": "02:59 PM",
      "label": "02:59 PM, Sep 19"
    }
  },
  {
    "date": "2032-10-04",
    "kind": "amavasya",
    "begins": {
      "date": "2032-10-03",
      "time": "04:50 PM",
      "label": "04:50 PM, Oct 03"
    },
    "ends": {
      "date": "2032-10-04",
      "time": "06:55 PM",
      "label": "06:55 PM, Oct 04"
    }
  },
  {
    "date": "2032-10-18",
    "kind": "purnima",
    "begins": {
      "date": "2032-10-18",
      "time": "03:26 AM",
      "label": "03:26 AM, Oct 18"
    },
    "ends": {
      "date": "2032-10-19",
      "time": "12:27 AM",
      "label": "12:27 AM, Oct 19"
    }
  },
  {
    "date": "2032-11-02",
    "kind": "amavasya",
    "begins": {
      "date": "2032-11-02",
      "time": "10:13 AM",
      "label": "10:13 AM, Nov 02"
    },
    "ends": {
      "date": "2032-11-03",
      "time": "11:14 AM",
      "label": "11:14 AM, Nov 03"
    }
  },
  {
    "date": "2032-11-17",
    "kind": "purnima",
    "begins": {
      "date": "2032-11-16",
      "time": "02:02 PM",
      "label": "02:02 PM, Nov 16"
    },
    "ends": {
      "date": "2032-11-17",
      "time": "12:11 PM",
      "label": "12:11 PM, Nov 17"
    }
  },
  {
    "date": "2032-12-02",
    "kind": "amavasya",
    "begins": {
      "date": "2032-12-02",
      "time": "02:53 AM",
      "label": "02:53 AM, Dec 02"
    },
    "ends": {
      "date": "2032-12-03",
      "time": "02:22 AM",
      "label": "02:22 AM, Dec 03"
    }
  },
  {
    "date": "2032-12-16",
    "kind": "purnima",
    "begins": {
      "date": "2032-12-16",
      "time": "02:48 AM",
      "label": "02:48 AM, Dec 16"
    },
    "ends": {
      "date": "2032-12-17",
      "time": "02:18 AM",
      "label": "02:18 AM, Dec 17"
    }
  }
];

export const lunarDays2033: LunarDay[] = [
  {
    "date": "2033-01-01",
    "kind": "amavasya",
    "begins": {
      "date": "2032-12-31",
      "time": "05:49 PM",
      "label": "05:49 PM, Dec 31"
    },
    "ends": {
      "date": "2033-01-01",
      "time": "03:46 PM",
      "label": "03:46 PM, Jan 01"
    }
  },
  {
    "date": "2033-01-15",
    "kind": "purnima",
    "begins": {
      "date": "2033-01-14",
      "time": "05:43 PM",
      "label": "05:43 PM, Jan 14"
    },
    "ends": {
      "date": "2033-01-15",
      "time": "06:36 PM",
      "label": "06:36 PM, Jan 15"
    }
  },
  {
    "date": "2033-01-30",
    "kind": "amavasya",
    "begins": {
      "date": "2033-01-30",
      "time": "06:39 AM",
      "label": "06:39 AM, Jan 30"
    },
    "ends": {
      "date": "2033-01-31",
      "time": "03:29 AM",
      "label": "03:29 AM, Jan 31"
    }
  },
  {
    "date": "2033-02-14",
    "kind": "purnima",
    "begins": {
      "date": "2033-02-13",
      "time": "10:31 AM",
      "label": "10:31 AM, Feb 13"
    },
    "ends": {
      "date": "2033-02-14",
      "time": "12:33 PM",
      "label": "12:33 PM, Feb 14"
    }
  },
  {
    "date": "2033-03-01",
    "kind": "amavasya",
    "begins": {
      "date": "2033-02-28",
      "time": "05:36 PM",
      "label": "05:36 PM, Feb 28"
    },
    "ends": {
      "date": "2033-03-01",
      "time": "01:52 PM",
      "label": "01:52 PM, Mar 01"
    }
  },
  {
    "date": "2033-03-15",
    "kind": "purnima",
    "begins": {
      "date": "2033-03-15",
      "time": "04:30 AM",
      "label": "04:30 AM, Mar 15"
    },
    "ends": {
      "date": "2033-03-16",
      "time": "07:06 AM",
      "label": "07:06 AM, Mar 16"
    }
  },
  {
    "date": "2033-03-30",
    "kind": "amavasya",
    "begins": {
      "date": "2033-03-30",
      "time": "03:04 AM",
      "label": "03:04 AM, Mar 30"
    },
    "ends": {
      "date": "2033-03-30",
      "time": "11:20 PM",
      "label": "11:20 PM, Mar 30"
    }
  },
  {
    "date": "2033-04-14",
    "kind": "purnima",
    "begins": {
      "date": "2033-04-13",
      "time": "10:25 PM",
      "label": "10:25 PM, Apr 13"
    },
    "ends": {
      "date": "2033-04-15",
      "time": "12:46 AM",
      "label": "12:46 AM, Apr 15"
    }
  },
  {
    "date": "2033-04-28",
    "kind": "amavasya",
    "begins": {
      "date": "2033-04-28",
      "time": "11:30 AM",
      "label": "11:30 AM, Apr 28"
    },
    "ends": {
      "date": "2033-04-29",
      "time": "08:15 AM",
      "label": "08:15 AM, Apr 29"
    }
  },
  {
    "date": "2033-05-14",
    "kind": "purnima",
    "begins": {
      "date": "2033-05-13",
      "time": "02:51 PM",
      "label": "02:51 PM, May 13"
    },
    "ends": {
      "date": "2033-05-14",
      "time": "04:11 PM",
      "label": "04:11 PM, May 14"
    }
  },
  {
    "date": "2033-05-28",
    "kind": "amavasya",
    "begins": {
      "date": "2033-05-27",
      "time": "07:30 PM",
      "label": "07:30 PM, May 27"
    },
    "ends": {
      "date": "2033-05-28",
      "time": "05:05 PM",
      "label": "05:05 PM, May 28"
    }
  },
  {
    "date": "2033-06-12",
    "kind": "purnima",
    "begins": {
      "date": "2033-06-12",
      "time": "04:53 AM",
      "label": "04:53 AM, Jun 12"
    },
    "ends": {
      "date": "2033-06-13",
      "time": "04:48 AM",
      "label": "04:48 AM, Jun 13"
    }
  },
  {
    "date": "2033-06-26",
    "kind": "amavasya",
    "begins": {
      "date": "2033-06-26",
      "time": "03:52 AM",
      "label": "03:52 AM, Jun 26"
    },
    "ends": {
      "date": "2033-06-27",
      "time": "02:36 AM",
      "label": "02:36 AM, Jun 27"
    }
  },
  {
    "date": "2033-07-12",
    "kind": "purnima",
    "begins": {
      "date": "2033-07-11",
      "time": "04:28 PM",
      "label": "04:28 PM, Jul 11"
    },
    "ends": {
      "date": "2033-07-12",
      "time": "02:57 PM",
      "label": "02:57 PM, Jul 12"
    }
  },
  {
    "date": "2033-07-25",
    "kind": "amavasya",
    "begins": {
      "date": "2033-07-25",
      "time": "01:36 PM",
      "label": "01:36 PM, Jul 25"
    },
    "ends": {
      "date": "2033-07-26",
      "time": "01:41 PM",
      "label": "01:41 PM, Jul 26"
    }
  },
  {
    "date": "2033-08-10",
    "kind": "purnima",
    "begins": {
      "date": "2033-08-10",
      "time": "02:17 AM",
      "label": "02:17 AM, Aug 10"
    },
    "ends": {
      "date": "2033-08-10",
      "time": "11:37 PM",
      "label": "11:37 PM, Aug 10"
    }
  },
  {
    "date": "2033-08-24",
    "kind": "amavasya",
    "begins": {
      "date": "2033-08-24",
      "time": "01:42 AM",
      "label": "01:42 AM, Aug 24"
    },
    "ends": {
      "date": "2033-08-25",
      "time": "03:09 AM",
      "label": "03:09 AM, Aug 25"
    }
  },
  {
    "date": "2033-09-09",
    "kind": "purnima",
    "begins": {
      "date": "2033-09-08",
      "time": "11:15 AM",
      "label": "11:15 AM, Sep 08"
    },
    "ends": {
      "date": "2033-09-09",
      "time": "07:49 AM",
      "label": "07:49 AM, Sep 09"
    }
  },
  {
    "date": "2033-09-23",
    "kind": "amavasya",
    "begins": {
      "date": "2033-09-22",
      "time": "04:43 PM",
      "label": "04:43 PM, Sep 22"
    },
    "ends": {
      "date": "2033-09-23",
      "time": "07:09 PM",
      "label": "07:09 PM, Sep 23"
    }
  },
  {
    "date": "2033-10-08",
    "kind": "purnima",
    "begins": {
      "date": "2033-10-07",
      "time": "08:12 PM",
      "label": "08:12 PM, Oct 07"
    },
    "ends": {
      "date": "2033-10-08",
      "time": "04:27 PM",
      "label": "04:27 PM, Oct 08"
    }
  },
  {
    "date": "2033-10-22",
    "kind": "amavasya",
    "begins": {
      "date": "2033-10-22",
      "time": "10:18 AM",
      "label": "10:18 AM, Oct 22"
    },
    "ends": {
      "date": "2033-10-23",
      "time": "12:57 PM",
      "label": "12:57 PM, Oct 23"
    }
  },
  {
    "date": "2033-11-06",
    "kind": "purnima",
    "begins": {
      "date": "2033-11-06",
      "time": "05:39 AM",
      "label": "05:39 AM, Nov 06"
    },
    "ends": {
      "date": "2033-11-07",
      "time": "02:01 AM",
      "label": "02:01 AM, Nov 07"
    }
  },
  {
    "date": "2033-11-21",
    "kind": "amavasya",
    "begins": {
      "date": "2033-11-21",
      "time": "05:08 AM",
      "label": "05:08 AM, Nov 21"
    },
    "ends": {
      "date": "2033-11-22",
      "time": "07:08 AM",
      "label": "07:08 AM, Nov 22"
    }
  },
  {
    "date": "2033-12-06",
    "kind": "purnima",
    "begins": {
      "date": "2033-12-05",
      "time": "03:52 PM",
      "label": "03:52 PM, Dec 05"
    },
    "ends": {
      "date": "2033-12-06",
      "time": "12:51 PM",
      "label": "12:51 PM, Dec 06"
    }
  },
  {
    "date": "2033-12-21",
    "kind": "amavasya",
    "begins": {
      "date": "2033-12-20",
      "time": "11:32 PM",
      "label": "11:32 PM, Dec 20"
    },
    "ends": {
      "date": "2033-12-22",
      "time": "12:15 AM",
      "label": "12:15 AM, Dec 22"
    }
  }
];

export const lunarDays2034: LunarDay[] = [
  {
    "date": "2034-01-04",
    "kind": "purnima",
    "begins": {
      "date": "2034-01-04",
      "time": "03:10 AM",
      "label": "03:10 AM, Jan 04"
    },
    "ends": {
      "date": "2034-01-05",
      "time": "01:16 AM",
      "label": "01:16 AM, Jan 05"
    }
  },
  {
    "date": "2034-01-20",
    "kind": "amavasya",
    "begins": {
      "date": "2034-01-19",
      "time": "04:15 PM",
      "label": "04:15 PM, Jan 19"
    },
    "ends": {
      "date": "2034-01-20",
      "time": "03:30 PM",
      "label": "03:30 PM, Jan 20"
    }
  },
  {
    "date": "2034-02-03",
    "kind": "purnima",
    "begins": {
      "date": "2034-02-02",
      "time": "03:58 PM",
      "label": "03:58 PM, Feb 02"
    },
    "ends": {
      "date": "2034-02-03",
      "time": "03:33 PM",
      "label": "03:33 PM, Feb 03"
    }
  },
  {
    "date": "2034-02-18",
    "kind": "amavasya",
    "begins": {
      "date": "2034-02-18",
      "time": "06:43 AM",
      "label": "06:43 AM, Feb 18"
    },
    "ends": {
      "date": "2034-02-19",
      "time": "04:39 AM",
      "label": "04:39 AM, Feb 19"
    }
  },
  {
    "date": "2034-03-04",
    "kind": "purnima",
    "begins": {
      "date": "2034-03-04",
      "time": "06:32 AM",
      "label": "06:32 AM, Mar 04"
    },
    "ends": {
      "date": "2034-03-05",
      "time": "07:39 AM",
      "label": "07:39 AM, Mar 05"
    }
  },
  {
    "date": "2034-03-20",
    "kind": "amavasya",
    "begins": {
      "date": "2034-03-19",
      "time": "06:48 PM",
      "label": "06:48 PM, Mar 19"
    },
    "ends": {
      "date": "2034-03-20",
      "time": "03:43 PM",
      "label": "03:43 PM, Mar 20"
    }
  },
  {
    "date": "2034-04-03",
    "kind": "purnima",
    "begins": {
      "date": "2034-04-02",
      "time": "10:35 PM",
      "label": "10:35 PM, Apr 02"
    },
    "ends": {
      "date": "2034-04-04",
      "time": "12:48 AM",
      "label": "12:48 AM, Apr 04"
    }
  },
  {
    "date": "2034-04-18",
    "kind": "amavasya",
    "begins": {
      "date": "2034-04-18",
      "time": "04:36 AM",
      "label": "04:36 AM, Apr 18"
    },
    "ends": {
      "date": "2034-04-19",
      "time": "12:55 AM",
      "label": "12:55 AM, Apr 19"
    }
  },
  {
    "date": "2034-05-03",
    "kind": "purnima",
    "begins": {
      "date": "2034-05-02",
      "time": "03:12 PM",
      "label": "03:12 PM, May 02"
    },
    "ends": {
      "date": "2034-05-03",
      "time": "05:44 PM",
      "label": "05:44 PM, May 03"
    }
  },
  {
    "date": "2034-05-17",
    "kind": "amavasya",
    "begins": {
      "date": "2034-05-17",
      "time": "12:31 PM",
      "label": "12:31 PM, May 17"
    },
    "ends": {
      "date": "2034-05-18",
      "time": "08:41 AM",
      "label": "08:41 AM, May 18"
    }
  },
  {
    "date": "2034-06-02",
    "kind": "purnima",
    "begins": {
      "date": "2034-06-01",
      "time": "07:16 AM",
      "label": "07:16 AM, Jun 01"
    },
    "ends": {
      "date": "2034-06-02",
      "time": "09:23 AM",
      "label": "09:23 AM, Jun 02"
    }
  },
  {
    "date": "2034-06-16",
    "kind": "amavasya",
    "begins": {
      "date": "2034-06-15",
      "time": "07:20 PM",
      "label": "07:20 PM, Jun 15"
    },
    "ends": {
      "date": "2034-06-16",
      "time": "03:55 PM",
      "label": "03:55 PM, Jun 16"
    }
  },
  {
    "date": "2034-07-01",
    "kind": "purnima",
    "begins": {
      "date": "2034-06-30",
      "time": "10:04 PM",
      "label": "10:04 PM, Jun 30"
    },
    "ends": {
      "date": "2034-07-01",
      "time": "11:13 PM",
      "label": "11:13 PM, Jul 01"
    }
  },
  {
    "date": "2034-07-15",
    "kind": "amavasya",
    "begins": {
      "date": "2034-07-15",
      "time": "02:15 AM",
      "label": "02:15 AM, Jul 15"
    },
    "ends": {
      "date": "2034-07-15",
      "time": "11:44 PM",
      "label": "11:44 PM, Jul 15"
    }
  },
  {
    "date": "2034-07-31",
    "kind": "purnima",
    "begins": {
      "date": "2034-07-30",
      "time": "11:27 AM",
      "label": "11:27 AM, Jul 30"
    },
    "ends": {
      "date": "2034-07-31",
      "time": "11:23 AM",
      "label": "11:23 AM, Jul 31"
    }
  },
  {
    "date": "2034-08-13",
    "kind": "amavasya",
    "begins": {
      "date": "2034-08-13",
      "time": "10:32 AM",
      "label": "10:32 AM, Aug 13"
    },
    "ends": {
      "date": "2034-08-14",
      "time": "09:22 AM",
      "label": "09:22 AM, Aug 14"
    }
  },
  {
    "date": "2034-08-29",
    "kind": "purnima",
    "begins": {
      "date": "2034-08-28",
      "time": "11:39 PM",
      "label": "11:39 PM, Aug 28"
    },
    "ends": {
      "date": "2034-08-29",
      "time": "10:18 PM",
      "label": "10:18 PM, Aug 29"
    }
  },
  {
    "date": "2034-09-12",
    "kind": "amavasya",
    "begins": {
      "date": "2034-09-11",
      "time": "09:22 PM",
      "label": "09:22 PM, Sep 11"
    },
    "ends": {
      "date": "2034-09-12",
      "time": "09:43 PM",
      "label": "09:43 PM, Sep 12"
    }
  },
  {
    "date": "2034-09-28",
    "kind": "purnima",
    "begins": {
      "date": "2034-09-27",
      "time": "10:59 AM",
      "label": "10:59 AM, Sep 27"
    },
    "ends": {
      "date": "2034-09-28",
      "time": "08:26 AM",
      "label": "08:26 AM, Sep 28"
    }
  },
  {
    "date": "2034-10-11",
    "kind": "amavasya",
    "begins": {
      "date": "2034-10-11",
      "time": "11:22 AM",
      "label": "11:22 AM, Oct 11"
    },
    "ends": {
      "date": "2034-10-12",
      "time": "01:01 PM",
      "label": "01:01 PM, Oct 12"
    }
  },
  {
    "date": "2034-10-27",
    "kind": "purnima",
    "begins": {
      "date": "2034-10-26",
      "time": "09:40 PM",
      "label": "09:40 PM, Oct 26"
    },
    "ends": {
      "date": "2034-10-27",
      "time": "06:11 PM",
      "label": "06:11 PM, Oct 27"
    }
  },
  {
    "date": "2034-11-10",
    "kind": "amavasya",
    "begins": {
      "date": "2034-11-10",
      "time": "04:19 AM",
      "label": "04:19 AM, Nov 10"
    },
    "ends": {
      "date": "2034-11-11",
      "time": "06:45 AM",
      "label": "06:45 AM, Nov 11"
    }
  },
  {
    "date": "2034-11-25",
    "kind": "purnima",
    "begins": {
      "date": "2034-11-25",
      "time": "07:56 AM",
      "label": "07:56 AM, Nov 25"
    },
    "ends": {
      "date": "2034-11-26",
      "time": "04:01 AM",
      "label": "04:01 AM, Nov 26"
    }
  },
  {
    "date": "2034-12-10",
    "kind": "amavasya",
    "begins": {
      "date": "2034-12-09",
      "time": "11:14 PM",
      "label": "11:14 PM, Dec 09"
    },
    "ends": {
      "date": "2034-12-11",
      "time": "01:43 AM",
      "label": "01:43 AM, Dec 11"
    }
  },
  {
    "date": "2034-12-25",
    "kind": "purnima",
    "begins": {
      "date": "2034-12-24",
      "time": "06:07 PM",
      "label": "06:07 PM, Dec 24"
    },
    "ends": {
      "date": "2034-12-25",
      "time": "02:23 PM",
      "label": "02:23 PM, Dec 25"
    }
  }
];

export const lunarDays2035: LunarDay[] = [
  {
    "date": "2035-01-09",
    "kind": "amavasya",
    "begins": {
      "date": "2035-01-08",
      "time": "06:39 PM",
      "label": "06:39 PM, Jan 08"
    },
    "ends": {
      "date": "2035-01-09",
      "time": "08:32 PM",
      "label": "08:32 PM, Jan 09"
    }
  },
  {
    "date": "2035-01-23",
    "kind": "purnima",
    "begins": {
      "date": "2035-01-23",
      "time": "04:39 AM",
      "label": "04:39 AM, Jan 23"
    },
    "ends": {
      "date": "2035-01-24",
      "time": "01:45 AM",
      "label": "01:45 AM, Jan 24"
    }
  },
  {
    "date": "2035-02-07",
    "kind": "amavasya",
    "begins": {
      "date": "2035-02-07",
      "time": "01:08 PM",
      "label": "01:08 PM, Feb 07"
    },
    "ends": {
      "date": "2035-02-08",
      "time": "01:51 PM",
      "label": "01:51 PM, Feb 08"
    }
  },
  {
    "date": "2035-02-22",
    "kind": "purnima",
    "begins": {
      "date": "2035-02-21",
      "time": "03:59 PM",
      "label": "03:59 PM, Feb 21"
    },
    "ends": {
      "date": "2035-02-22",
      "time": "02:23 PM",
      "label": "02:23 PM, Feb 22"
    }
  },
  {
    "date": "2035-03-09",
    "kind": "amavasya",
    "begins": {
      "date": "2035-03-09",
      "time": "05:22 AM",
      "label": "05:22 AM, Mar 09"
    },
    "ends": {
      "date": "2035-03-10",
      "time": "04:38 AM",
      "label": "04:38 AM, Mar 10"
    }
  },
  {
    "date": "2035-03-23",
    "kind": "purnima",
    "begins": {
      "date": "2035-03-23",
      "time": "04:21 AM",
      "label": "04:21 AM, Mar 23"
    },
    "ends": {
      "date": "2035-03-24",
      "time": "04:11 AM",
      "label": "04:11 AM, Mar 24"
    }
  },
  {
    "date": "2035-04-08",
    "kind": "amavasya",
    "begins": {
      "date": "2035-04-07",
      "time": "06:37 PM",
      "label": "06:37 PM, Apr 07"
    },
    "ends": {
      "date": "2035-04-08",
      "time": "04:26 PM",
      "label": "04:26 PM, Apr 08"
    }
  },
  {
    "date": "2035-04-22",
    "kind": "purnima",
    "begins": {
      "date": "2035-04-21",
      "time": "05:43 PM",
      "label": "05:43 PM, Apr 21"
    },
    "ends": {
      "date": "2035-04-22",
      "time": "06:49 PM",
      "label": "06:49 PM, Apr 22"
    }
  },
  {
    "date": "2035-05-07",
    "kind": "amavasya",
    "begins": {
      "date": "2035-05-07",
      "time": "04:49 AM",
      "label": "04:49 AM, May 07"
    },
    "ends": {
      "date": "2035-05-08",
      "time": "01:33 AM",
      "label": "01:33 AM, May 08"
    }
  },
  {
    "date": "2035-05-22",
    "kind": "purnima",
    "begins": {
      "date": "2035-05-21",
      "time": "07:55 AM",
      "label": "07:55 AM, May 21"
    },
    "ends": {
      "date": "2035-05-22",
      "time": "09:55 AM",
      "label": "09:55 AM, May 22"
    }
  },
  {
    "date": "2035-06-05",
    "kind": "amavasya",
    "begins": {
      "date": "2035-06-05",
      "time": "12:41 PM",
      "label": "12:41 PM, Jun 05"
    },
    "ends": {
      "date": "2035-06-06",
      "time": "08:49 AM",
      "label": "08:49 AM, Jun 06"
    }
  },
  {
    "date": "2035-06-20",
    "kind": "purnima",
    "begins": {
      "date": "2035-06-19",
      "time": "10:44 PM",
      "label": "10:44 PM, Jun 19"
    },
    "ends": {
      "date": "2035-06-21",
      "time": "01:06 AM",
      "label": "01:06 AM, Jun 21"
    }
  },
  {
    "date": "2035-07-05",
    "kind": "amavasya",
    "begins": {
      "date": "2035-07-04",
      "time": "07:19 PM",
      "label": "07:19 PM, Jul 04"
    },
    "ends": {
      "date": "2035-07-05",
      "time": "03:28 PM",
      "label": "03:28 PM, Jul 05"
    }
  },
  {
    "date": "2035-07-20",
    "kind": "purnima",
    "begins": {
      "date": "2035-07-19",
      "time": "01:56 PM",
      "label": "01:56 PM, Jul 19"
    },
    "ends": {
      "date": "2035-07-20",
      "time": "04:06 PM",
      "label": "04:06 PM, Jul 20"
    }
  },
  {
    "date": "2035-08-03",
    "kind": "amavasya",
    "begins": {
      "date": "2035-08-03",
      "time": "01:58 AM",
      "label": "01:58 AM, Aug 03"
    },
    "ends": {
      "date": "2035-08-03",
      "time": "10:40 PM",
      "label": "10:40 PM, Aug 03"
    }
  },
  {
    "date": "2035-08-18",
    "kind": "purnima",
    "begins": {
      "date": "2035-08-18",
      "time": "05:08 AM",
      "label": "05:08 AM, Aug 18"
    },
    "ends": {
      "date": "2035-08-19",
      "time": "06:29 AM",
      "label": "06:29 AM, Aug 19"
    }
  },
  {
    "date": "2035-09-01",
    "kind": "amavasya",
    "begins": {
      "date": "2035-09-01",
      "time": "09:46 AM",
      "label": "09:46 AM, Sep 01"
    },
    "ends": {
      "date": "2035-09-02",
      "time": "07:28 AM",
      "label": "07:28 AM, Sep 02"
    }
  },
  {
    "date": "2035-09-17",
    "kind": "purnima",
    "begins": {
      "date": "2035-09-16",
      "time": "07:50 PM",
      "label": "07:50 PM, Sep 16"
    },
    "ends": {
      "date": "2035-09-17",
      "time": "07:52 PM",
      "label": "07:52 PM, Sep 17"
    }
  },
  {
    "date": "2035-10-01",
    "kind": "amavasya",
    "begins": {
      "date": "2035-09-30",
      "time": "07:37 PM",
      "label": "07:37 PM, Sep 30"
    },
    "ends": {
      "date": "2035-10-01",
      "time": "06:36 PM",
      "label": "06:36 PM, Oct 01"
    }
  },
  {
    "date": "2035-10-17",
    "kind": "purnima",
    "begins": {
      "date": "2035-10-16",
      "time": "09:33 AM",
      "label": "09:33 AM, Oct 16"
    },
    "ends": {
      "date": "2035-10-17",
      "time": "08:04 AM",
      "label": "08:04 AM, Oct 17"
    }
  },
  {
    "date": "2035-10-30",
    "kind": "amavasya",
    "begins": {
      "date": "2035-10-30",
      "time": "08:07 AM",
      "label": "08:07 AM, Oct 30"
    },
    "ends": {
      "date": "2035-10-31",
      "time": "08:27 AM",
      "label": "08:27 AM, Oct 31"
    }
  },
  {
    "date": "2035-11-15",
    "kind": "purnima",
    "begins": {
      "date": "2035-11-14",
      "time": "10:05 PM",
      "label": "10:05 PM, Nov 14"
    },
    "ends": {
      "date": "2035-11-15",
      "time": "07:18 PM",
      "label": "07:18 PM, Nov 15"
    }
  },
  {
    "date": "2035-11-29",
    "kind": "amavasya",
    "begins": {
      "date": "2035-11-28",
      "time": "11:30 PM",
      "label": "11:30 PM, Nov 28"
    },
    "ends": {
      "date": "2035-11-30",
      "time": "01:06 AM",
      "label": "01:06 AM, Nov 30"
    }
  },
  {
    "date": "2035-12-14",
    "kind": "purnima",
    "begins": {
      "date": "2035-12-14",
      "time": "09:39 AM",
      "label": "09:39 AM, Dec 14"
    },
    "ends": {
      "date": "2035-12-15",
      "time": "06:02 AM",
      "label": "06:02 AM, Dec 15"
    }
  },
  {
    "date": "2035-12-29",
    "kind": "amavasya",
    "begins": {
      "date": "2035-12-28",
      "time": "05:31 PM",
      "label": "05:31 PM, Dec 28"
    },
    "ends": {
      "date": "2035-12-29",
      "time": "08:00 PM",
      "label": "08:00 PM, Dec 29"
    }
  }
];

export const ALL_LUNAR_DAYS: LunarDay[] = [...lunarDays2025, ...lunarDays2026, ...lunarDays2027, ...lunarDays2028, ...lunarDays2029, ...lunarDays2030, ...lunarDays2031, ...lunarDays2032, ...lunarDays2033, ...lunarDays2034, ...lunarDays2035];

export const ALL_PURNIMA_DATES: string[] = ALL_LUNAR_DAYS.filter((day) => day.kind === "purnima").map((day) => day.date);
export const ALL_AMAVASYA_DATES: string[] = ALL_LUNAR_DAYS.filter((day) => day.kind === "amavasya").map((day) => day.date);

const LUNAR_BY_DATE = new Map(ALL_LUNAR_DAYS.map((day) => [day.date, day]));

export function getLunarDayForDate(date: string): LunarDay | undefined {
  return LUNAR_BY_DATE.get(date);
}

export function getLunarKindForDate(date: string): LunarDayKind | undefined {
  return getLunarDayForDate(date)?.kind;
}

export function getLunarDaysForMonth(monthKey: string): LunarDay[] {
  return ALL_LUNAR_DAYS.filter((day) => day.date.startsWith(monthKey)).sort((a, b) => a.date.localeCompare(b.date));
}

export function formatLunarTiming(timing: LunarTiming): string {
  return timing.label;
}
